spring.application.name=id_card_service
server.port=8085
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
server.address=192.168.0.143
spring.servlet.multipart.max-file-size=11MB
spring.servlet.multipart.max-request-size=11MB
